cargo-features = ["edition"]

[package]
name = "futures-core"
version = "0.2.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
The core traits and types in for the `futures` library.
"""
edition = "2018"

[features]
default = ["std"]
std = ["either/use_std"]
nightly = []

[dependencies]
either = { version = "1.4", default-features = false, optional = true }
